random_state: 42
cv:
  folds: 5
  shuffle: true
scaler: "standard"       # standard | minmax | none
selector:
  method: "kbest"        # kbest | rfe | none
  k: 50
  estimator: "logreg"    # used for RFE if selected
models:
  - name: "svm_rbf"
    type: "svm"
    params:
      C: 1.0
      kernel: "rbf"
      gamma: "scale"
  - name: "random_forest"
    type: "rf"
    params:
      n_estimators: 200
      max_depth: null
      n_jobs: -1
metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1"
  - "roc_auc"
